### PR TITLE
Feature/reset upgrades

### PR DESCRIPTION
**Pull request by matthewpeterkort**
~~Adds granular reset and normalization to the util.~~

~~ie: assuming that you have 2+ local commits you can reset to the 1st or later commit state via~~

~~`g3t reset 901d4d5c1121513df8151f734e8fe928` where 901d4d5c1121513df8151f734e8fe928 is the commit id of the first commit.~~

~~So essentially it is g3t reset [commit_id of commit you want to go back to]~~

or if you want to remove all commits ever for a project you can do 

`g3t reset --all`

~~Should probably rework this to also support reset for the last local commit that has been made too. Currently you can reset to the last local commit so long as there is a local commit before the commit you are resetting to~~

See: 
https://github.com/ACED-IDP/submission/pull/18
https://github.com/ACED-IDP/aced_etl_pod/pull/28

~~Spent a few hours trying to get the granular pytest to pass. Not sure exactly why it fails in pytest. The command works fine in real world testing~~

Also includes added detail to exception catching and changing print statements to echo statements

### CODE REVIEW

**Review by bwalsh — COMMENTED** [review]
MP:  this all looks great.  I'm going to hold off approving (merge to development until we get some more testing)

**Comment by bwalsh** [comment]
@matthewpeterkort We discussed merging this when I got back from vacation.   You indicated it was not appropriate.  Please close the PR

**Comment by matthewpeterkort** [comment]
> @matthewpeterkort We discussed merging this when I got back from vacation. You indicated it was not appropriate. Please close the PR

There are some parts of this PR like better exception handling, and click.echo consolidation that should get merged. The reset command `g3t reset --all` should be kept. The granular reset would probably cause more harm than good and should be removed. Will clean up this PR more to reflect that.

**Comment by matthewpeterkort** [comment]
util went another direction. Closing

**Pull request closed without merging**
